services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbstu-app
    restart: unless-stopped
    volumes:
      - ./laravel-vue:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mbstu-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: mbstu-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel-vue:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mbstu-network
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: mbstu-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mbstu_db
      POSTGRES_USER: mbstu_user
      POSTGRES_PASSWORD: mbstu_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - mbstu_postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - mbstu-network

  adminer:
    image: adminer:latest
    container_name: mbstu-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - mbstu-network
    depends_on:
      - db

networks:
  mbstu-network:
    driver: bridge

volumes:
  mbstu_postgres:
    driver: local
